In [18]:
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV, train_test_split

In [19]:
X, y = make_classification(n_samples=100, n_features=4,
                           n_informative=2, n_redundant=0,
                            random_state=0, shuffle=False)
print(X)
print(y)

[[ 4.22341441e-01 -2.05321581e+00  9.10178908e-01  3.17218215e-01]
 [-1.25732069e+00 -3.19826339e+00  7.86327962e-01 -4.66419097e-01]
 [ 1.23195055e+00 -9.95105317e-01 -9.44446256e-01 -4.10049693e-01]
 [-4.37843295e-02 -1.27395967e+00 -1.70204139e-02  3.79151736e-01]
 [-1.30819171e+00 -1.28532883e+00  2.25930895e+00 -4.22571517e-02]
 [-1.62073375e+00 -2.22244349e+00 -9.55945000e-01 -3.45981776e-01]
 [-3.59967304e-01 -1.41363563e+00 -4.63595975e-01  4.81481474e-01]
 [-7.62884416e-01 -1.45125944e+00 -1.54079701e+00  6.32619942e-02]
 [ 4.86681188e-01 -1.45709006e+00  1.56506538e-01  2.32181036e-01]
 [-2.68051210e-01 -4.47369310e-01 -5.97316069e-01 -2.37921730e-01]
 [-3.69743600e+00 -4.61220130e-01 -1.42406091e+00 -4.93319883e-01]
 [ 1.83324682e-01 -7.66054695e-01 -5.42861476e-01  4.16050046e-01]
 [ 1.85082392e+00 -7.80910684e-01 -1.15618243e+00  7.81198102e-01]
 [-8.60699619e-01 -8.69385004e-01  1.49448454e+00 -2.06998503e+00]
 [-3.45538051e-01 -2.81180710e+00  4.26258731e-01  6.76908035e

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=123)
print(X_train[:5])


[[-3.58754622 -1.85016853  0.14195316 -0.31932842]
 [ 1.10698637 -0.53583409  0.56729028 -0.2226751 ]
 [ 0.73389996 -0.13650855  0.49374178 -0.11610394]
 [ 1.78037474 -0.90014214  0.5785215   0.34965446]
 [ 2.03196825  2.1871814  -0.20690368  0.88017891]]


In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)
X_train[:5]

In [ ]:
clf = BaggingClassifier(base_estimator=SVC(gamma=0.5),
                         n_estimators=10, random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)


In [ ]:
from sklearn.model_selection import GridSearchCV
import numpy as np

clf = BaggingClassifier(base_estimator=SVC(kernel='rbf',C=1,gamma=0.5))

num = np.arange(5,20,1)
param_grid = [{'n_estimators':num}]
# 网格搜索交叉验证的参数范围，cv=3,3折交叉
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv=3, n_jobs=-1)
# 训练模型
grid.fit(X_train, y_train)

# 计算测试集精度，利用最优的
y_pred = grid.predict(X_test)
print(accuracy_score(y_pred,y_test))

In [ ]:
import pandas as pd

print(grid.best_score_,grid.best_params_)
params = grid.cv_results_['params']
scores = grid.cv_results_['mean_test_score']
# print(params)
#想办法把scores弄进去
list = []
for param, score in zip(params, scores):
    param['score']=score
    list.append(param)
pd.DataFrame(list)

In [25]:
import pandas as pd

print(grid.best_score_,grid.best_params_)
params = grid.cv_results_['params']
scores = grid.cv_results_['mean_test_score']
# print(params)
#想办法把scores弄进去
list = []
for param, score in zip(params, scores):
    param['score']=score
    list.append(param)
pd.DataFrame(list)

array([[-2.79786143, -1.3436652 ,  0.42361507, -0.24162223],
       [ 0.88712169, -0.35390428,  0.88164086, -0.13980427],
       [ 0.59426673, -0.05319176,  0.8024399 , -0.0275385 ],
       [ 1.41569929, -0.62824684,  0.89373524,  0.4631076 ],
       [ 1.61318814,  1.69666538,  0.04794734,  1.02198051]])

In [50]:
clf = BaggingClassifier(base_estimator=SVC(gamma=0.5),
                         n_estimators=10, random_state=0).fit(X_train, y_train)
clf.score(X_test,y_test)


0.8

In [52]:
from sklearn.model_selection import GridSearchCV
import numpy as np

clf = BaggingClassifier(base_estimator=SVC(kernel='rbf',C=1,gamma=0.5))

num = np.arange(5,20,1)
param_grid = [{'n_estimators':num}]
# 网格搜索交叉验证的参数范围，cv=3,3折交叉
grid = GridSearchCV(estimator=clf, param_grid=param_grid, cv=3, n_jobs=-1)
# 训练模型
grid.fit(X_train, y_train)

# 计算测试集精度，利用最优的
y_pred = grid.predict(X_test)
print(accuracy_score(y_pred,y_test))

0.8333333333333334


D:\APP\Anaconda3\py37\tensorflow-gpu\lib\site-packages\sklearn\model_selection\_search.py:842: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [48]:
import pandas as pd

print(grid.best_score_,grid.best_params_)
params = grid.cv_results_['params']
scores = grid.cv_results_['mean_test_score']
# print(params)
#想办法把scores弄进去
list = []
for param, score in zip(params, scores):
    param['score']=score
    list.append(param)
pd.DataFrame(list)

0.8714285714285714 {'n_estimators': 18}


n_estimators     score
0              5  0.828571
1              6  0.857143
2              7  0.814286
3              8  0.857143
4              9  0.814286
5             10  0.842857
6             11  0.857143
7             12  0.828571
8             13  0.842857
9             14  0.800000
10            15  0.814286
11            16  0.842857
12            17  0.857143
13            18  0.871429
14            19  0.871429